### ISSUE TITLE
Cant import maven project.Maybe trouble is in this link,that doesnt works https://repo.glowstone.net/repository/internal/

### ISSUE THREAD

**Issue by errorman-awful** [GlowstoneMC/Glowstone#1103]
![Screenshot_13](https://user-images.githubusercontent.com/44864773/100554017-fa474e80-32a2-11eb-8870-e608b4cbced8.png)

**Comment by mastercoms** [comment]
We no longer use `internal`. You can use https://repo.glowstone.net/repository/snapshots/ instead for Glowkit and Flow Network, and https://repo.glowstone.net/repository/destroystokyo-releases/ instead for fastutil-lite.

Could you point me to where you saw to use `internal`, so that I may update it?
