### ISSUE TITLE
Sunflower

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#14]
So there was a discussion on how to implement new APIs with Glowstone. I suggested having Glowstone being able to load multiple APIs and translate these methods to an internal API, but the collaborators of Glowstone decided that they were going to only use Bukkit until Glowstone was stable, so I decided to work on a new implementation which I never got around to.

[Sunflower](https://github.com/SunflowerMC).

Sunflower was planned to create a universal wrapper for a server using mappings that would translate methods to that server's internal API. In this case, Bukkit.

Unfortunately, I am extremely busy and couldn't work on anything besides some pseudo code and planning.

So, I was wondering if GlowstonePlusPlus could be the Sunflower server, [Helios](https://github.com/SunflowerMC/Helios). Just like Craftbukkit++ transformed into Spigot, Glowstone++ can transform into Helios. Of course, I'm completely fine if @deathcap is not ok with it, and I guess I'll delete Sunflower because I won't have a chance to work on it, and I will work on Glowstone++ instead.

**Comment by mastercoms** [comment]
I will make GlowBridge instead.

**Comment by deathcap** [comment]
Saw your announcement on Reddit https://www.reddit.com/r/admincraft/comments/2zx2z0/i_just_started_planning_sunflower_an_api_to/

Looks like an interesting concept but how are you planning on doing the bridging exactly?

**Comment by mastercoms** [comment]
Well I don't really have exact thoughts on methods in the code but it would just return the respective mapped method for either bukkit or sponge or whatever.

**Comment by deathcap** [comment]
@mastercoms if you can develop a prototype, would be something to consider. There is some method mapping in Glowstone, Spigot, and Sponge for what it's worth, they use it to overload return values for legacy Bukkit API:

* https://github.com/GlowstoneMC/GlowRemapper - Gradle plugin, used in Glowstone
* https://github.com/LapisBlue/Remapper - LapisBlue's (developers of Pore, a Sponge plugin implementing Bukkit) fork of GlowRemapper
* https://github.com/agaricusb/SpecialSourceMP - Maven plugin, used in Spigot and Glowstone++

but I am not sure if this technique could feasibly be used to map between Sponge and Bukkit APIs, because it is not a straightforward matter of symbol naming differences, but the classes implement different interfaces. 

Playing around with another approach, a Bukkit plugin implementing SpongeAPI: https://github.com/deathcap/Bukkit2Sponge

**Comment by mastercoms** [comment]
There are two things to consider, plugins and Glowstone itself. Glowstone will be quite easy to implement other APIs, as we have control over what we import and the names of everything. So we can change imports to org.sunflower.* and then in Sunflower code the toggles for different APIs. 

However, for plugins, we can't control their code. The simplest way to solve this problem is to put Sunflower in every place a plugin would import, such as in org.bukkit and org.spongepowered, although that is pretty horrible.

**Comment by deathcap** [comment]
OK I think I have an idea of how the plugin-API/server-implementation could be separated, along the lines of what you might had envisioned for Sunflower.

Not sure if this is feasible, but let me know what you think: first isolate the Glowstone++ server so it can load and run without any plugin APIs, then add plugin API implementations (Bukkit, Sponge, Canary, Forge, Nova) on top, possibly in a separate subproject. Each of the plugin APIs could be added or removed independently and new plugin API implementations could be developed on equal standing. They would essentially be "plugin-API plugins" for the Glowstone++ server itself.

The main challenge of course with this design is interfacing the plugin APIs with the server. *Some* kind of interface is needed, though it doesn't have to be stable or comprehensive, only enough to allow the plugin API addons to be written. Another challenge is removing the remnants of the Bukkit API dependency in the server implementation. Started this on https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/tree/nobukkit but easier said than done. Some data types from the Bukkit API are used in the server directly with no implementation-specific derivative (such as the GameType enum, granted easily replaced, moved into the server), and also some implementation code from the Bukkit "API" such as SimpleCommandMap. A Bukkit-free Glowstone++ could be an interesting step towards this kind of architecture, but its no small feat.

Another option, since an API would be needed to support plugin-API addons anyways, why not just use the Bukkit API for this purpose? That is, other plugin APIs could be written on top of the "Bukkit" API, like Bukkit2Sponge. Since Glowstone++ has its own fork of Glowkit/Bukkit, the API can be enhanced as needed to support new functionality required by the other plugin APIs (titles, action messages, etc). This would also help the Bukkit API grow and develop and get more testing, stabilizing to better support Bukkit plugins. The downside though is if the Bukkit API is inefficient or poorly designed in some areas, inhibiting development of better plugin APIs through a suboptimal bridging layer. Thoughts?

**Comment by mastercoms** [comment]
My goal with Sunflower was to make a API agnostic server, with the possibility of being version agnostic, too. It would be a wrapper for other servers, including the vanilla one, and would work by starting it like this:
```
java -jar Sunflower.jar minecraft_server.jar
```
It would then create a folder called mappings, and a file called sunflower.yml. In sunflower.yml, there would be these config lines
```
api: [bukkit, sponge]
server: vanilla
```
Then in mappings, there would be vanilla.json, bukkit.json, and sponge.json.
It would look something like this: https://github.com/GranitePowered/GraniteMappings/blob/master/1.8.json
It would basically normalize all the differences in APIs/servers to a common interface name, which Sunflower would use to inject the API into the server.
Then in a folder called api, there would be actually api files.

Perhaps it could look something like this, but instead of a wrapper, we do it in the fashion you suggested, with plugins instead of the plugin manager being integrated into the actual server, as there might be some quirks with an API that will have to be solved specifically and programmatically for that API using a plugin, and each plugin would include its own mappings thing and obviously the api files.

**Comment by mastercoms** [comment]
Sunflower is no longer related to this discussion about APIs, I am making an API issue now.
