### ISSUE TITLE
By default, rain is on

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#15]
Every world's downfall is true when it is created. This causes for rain to always be enabled by default.

**Comment by deathcap** [comment]
Noticed this too, also it is night by default, so every world starts out as a dark and stormy night, quite annoying, having to run /toggledownfall then /time set 10000 to get back to a bright and sunny day for a pleasant testing or development session. Looks like this happens because in src/main/java/net/glowstone/GlowWorld.java:

```javascript
    /**
     * How many ticks until the rain/snow status is expected to change.
     */
    private int rainingTicks = 0;

   /**
     * Whether it is currently raining/snowing on this world.
     */
    private boolean currentlyRaining = false;

…

            if (--rainingTicks <= 0) {
                setStorm(!currentlyRaining);
            }
```

so a rain transition from false to true occurs almost immediately

**Comment by mastercoms** [comment]
So a quick fix would be to turn currentlyRaining to true?

**Comment by deathcap** [comment]
Seems so (untested). Another fix might be to initialize rainingTicks to its max value but this number is hard coded elsewhere in the code (should be pulled out into a constant?).

**Comment by deathcap** [comment]
Pushed that fix for now, seems to work well, but if the events (WeatherChangeEvent and ThunderChangeEvent) being sent on each new world cause problems may have to investigate a different fix.

**Comment by TekkitCommando** [comment]
deathcap i have a question
