### ISSUE TITLE
Replicating pickaxe

### ISSUE THREAD

**Issue by Rocologo** [GlowstoneMC/Glowstone#311]
And then I tried to mine some cobblestone with a wooden pickaxe. And I found this error:

1) mine cobblestone until the pickaxe breaks
2) when you pick up the cobblestone you also get a pickaxe???

No errors thrown in the console

When I later cut some wood with the pickaxe I didnt see this behavior.

The same happened when I tried with a stone pickaxe

**Comment by tsengia** [comment]
If someone could assign this to me and update waffle accordingly. I'd like to test and squash this bug.

**Comment by tsengia** [comment]
I've also noticed that if you pause after mining stone, when you pick up the cobblestone, your pickaxe resets it's durability to full durability.

**Comment by mastercoms** [comment]
The pickaxe isn't resetting the durability. The client thinks that the pickaxe's durability decreases, but when you pick up an item, it syncs its inventory state with the server, and finds that the pickaxe is at full durability. Something broke with our durability code.

**Comment by tsengia** [comment]
https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/net/handler/play/player/DiggingHandler.java#L114-128
We have no checks to see if the item in hand is a tool or not, so if you're holding a birch log and you break a wood block with it, your birch log will take durability and "break"? Maybe I'm missing something, but still, there are no checks to see if the item in hand is a tool or not

**Comment by olliestanley** [comment]
Wouldn't the durability != max durability check at https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/net/handler/play/player/DiggingHandler.java#L93 cancel out non-tools?

**Comment by tsengia** [comment]
@DziNeIT No, I don't think so, but I do think that `!=` is the source of the issue. That expression is meant to check if the current durability of the item in hand is over/at the max durability. However, since it is a `!=` it only works when the current durability and max durability are the _same_. I'm testing to see if replacing the `!=` with a `<` would do

**Comment by olliestanley** [comment]
@ExpandingDev No, it works when the current durability and max durability are not the same (you said it works when they are the same - typo?)

**Comment by tsengia** [comment]
@DziNeIT Oh, I meant by "works" as in it prevents a broken tool to be used to mine the block. So if the tool is broken because its durability is over its max, it will still register as not broken in that expression (note, just in that expression, idk where the item/tool break methods are, which is probably the next place to look)

**Comment by olliestanley** [comment]
@ExpandingDev Oh I get it haha, my bad

**Comment by tsengia** [comment]
https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/block/itemtype/ItemTool.java#L32-42
That looks useful, maybe instead of manually setting the item/tool durability, we could utilize this function instead.

**Comment by mastercoms** [comment]
It cancels out non-tools. Items without durability will have a max durability and durability of 0, while stuff like tools will have a durability of 0 and a max durability of 255, for example.
