### ISSUE TITLE
Entity#setGravity(false) leaves gravity enabled

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#454]
When `.setGravity(false)` is called on an `Entity`, physics are supposed to be disabled allowing the entity to float mid-air, but instead the call appears to have no effect and entities still fall to the ground.

Looking at the code, https://github.com/GlowstoneMC/Glowstone/blob/47b0e0b699d607f9d1d196a1aa9897d055928aa9/src/main/java/net/glowstone/entity/GlowEntity.java#L1056 setGravity sets `this.gravity` but I can't find where it is accessed, may be a simple check `if (this.gravity)` that is missing surrounding the relevant physics code.

Glowstone build 444

**Comment by VaiTon** [comment]
> physics are supposed to be disabled

Not all physics, just gravity, so that entities can be still pushed (TNT, other entities, damage, water, etc...)

[Here](http://gph.is/2oxmkTu) is an example
So we should modify only these two lines ([1](https://github.com/GlowstoneMC/Glowstone/blob/47b0e0b699d607f9d1d196a1aa9897d055928aa9/src/main/java/net/glowstone/entity/GlowEntity.java#L720) , [2](https://github.com/GlowstoneMC/Glowstone/blob/47b0e0b699d607f9d1d196a1aa9897d055928aa9/src/main/java/net/glowstone/entity/GlowEntity.java#L774))

**Comment by mastercoms** [comment]
Yep, I forgot about that method.
