### ISSUE TITLE
/tp is no longer a recognized command (missing alias?)

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#494]
Glowstone 544 (1.12), the /tp command is now unknown:

```
>tp
21:31:14 [INFO] Unknown command "tp", try "help"
```

I see there is a [TeleportCommand](https://github.com/GlowstoneMC/Glowstone/blob/b01b8fe825da866f98ae3c736040f50020333faa/src/main/java/net/glowstone/command/minecraft/TeleportCommand.java) and /teleport works, so this may be a matter of aliasing commands not working correctly?

**Comment by mastercoms** [comment]
No alias was registered for TeleportCommand, so it isn't a result of aliasing commands not working correctly.

**Comment by aramperes** [comment]
[`/teleport`](http://minecraft.gamepedia.com/Commands#teleport) is a different command than `/tp` (they have different uses and functionality). Since 1.12, Spigot has removed all command implementations from Bukkit.

We will be adding these commands back progressively, but as of right now, `/tp` has not been implemented in Glowstone.

**Comment by aramperes** [comment]
Closing in favor of #499
