### ISSUE TITLE
Question about the future of Glowstone++

### ISSUE THREAD

**Issue by ethsmith** [GlowstoneMC/Glowstone#50]
So is there plans for Glowstone++ to be a major thing or is this only for fun because I really want to help out if you have plans to make Glowstone++ a big thing. Things that could help with the success
Of Glowstone++ could be a website, irc chat, official test servers, Github organization so that who's on the Glowstone++ team will be easily defined and you can do a lot more with permissions on repos if a github organization is created. Just wondering :P

**Comment by mastercoms** [comment]
I guess for right now, we want to expand Glowstone++'s code and then worry about a website, though I have one in the works.

**Comment by deathcap** [comment]
A GitHub organization sounds like a good idea, I created one and moved this repository there https://github.com/GlowstonePlusPlus/GlowstonePlusPlus (https://github.com/deathcap/GlowstonePlusPlus redirects so links shouldn't be broken), added you @TekkitCommando @mastercoms and @jimmikaelkael 

Although to be honest, I'm kind of losing interest, or maybe not necessarily interest but momentum. Originally I was interested in Glowstone since it seems to be the most promising open source Minecraft-compatible server, especially with its Bukkit plugin support (and now Spigot GH-5 and partial Sponge GH-47 support with Glowstone++), so I was investigating using it as the server backend for the [voxelmetaverse](https://github.com/deathcap/voxelmetaverse), part of the [voxeljs](http://voxeljs.com) ecosystem, all I would need to do is write a [web-based Minecraft-compatible client](https://github.com/deathcap/voxel-clientmc) (largely building on [PrismarineJS](https://github.com/PrismarineJS/node-minecraft-protocol)) in order to have a fully 100% open source complete Minecraft-compatible stack, with Glowstone++ as the server foundation. I still think this is a compelling idea, but there's a long way to go. At least it's open source so the projects can continue without me if needed =)

For test servers, GH-39 and GH-42. For chat, maybe https://gitter.im? (PrismarineJS uses it, works well, easily usable on the web so no separate client is needed). A website would be cool, too

**Comment by TekkitCommando** [comment]
We can start working on all this, if the word gets out and more devs get interested you won't be required to do all the work possibly. :)

**Comment by TekkitCommando** [comment]
And for IRC I am mostly interested In Gitter.im or EsperNet :)

**Comment by TekkitCommando** [comment]
Esper seems to be the most popular

**Comment by TekkitCommando** [comment]
@mastercoms cool! I want to see it whenever it's ready :D
