### ISSUE TITLE
Question about branch nobukkit 

### ISSUE THREAD

**Issue by kamcio96** [GlowstoneMC/Glowstone#70]
what will it contain? only SpongeAPI and implementation?

**Comment by mastercoms** [comment]
I am not sure, you can ask @deathcap, but I think it is just a API agnostic implementation of Glowstone.

**Comment by deathcap** [comment]
It was an attempt at removing the Bukkit API dependency of Glowstone, as an intermediate step so SpongeAPI could be added on top without also having to interoperate with Bukkit API support, but it turns out to be a larger task than expected since Glowstone intimately relies on Bukkit API implementation details. For now I think https://github.com/GlowstonePlusPlus/Bukkit2Sponge is a better approach going forward
