### ISSUE TITLE
Huge memory leaks

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#71]
There are two huge memory leaks in Glowstone++ right now.

I don't know what causes them yet, but the objects/classes created are:
- io.netty.util.Recycler$WeakOrderQueue
- io.netty.util.Recycler$WeakOrderQueue$Link
- java.lang.ref.Finalizer

Glowstone does have the java.lang.ref.Finalizer leak. I should mention that this leak does not grow nearly as fast as the netty leak.

[Information](https://stackoverflow.com/questions/8355064/is-memory-leak-why-java-lang-ref-finalizer-eat-so-much-memory) on memory leaks with Finalizer.

I haven't been able to find much about the netty stuff, but here's the [class file](http://netty.io/4.0/xref/io/netty/util/Recycler.html).

This is not a problem directly caused by Glowstone++. We could be using a library in a wrong manner.

The memory usage climbs fairly linearly. I've seen the eden space grow to 1GB sometimes, from around 7MB.

It only happens while a player is on the server.

**Comment by mastercoms** [comment]
This is really out of our control, we can't do anything about it except use optimized start scripts.

**Comment by maytal-shamir** [comment]
Hi,

Have you found any solution for this leak?

I think I'm having the same issue because I'm getting this error:
DEBUG[cb-io-1-1] c.c.c.c.e.AbstractGenericHandler: Channel Active.
sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,port=0,localport=52557] throws
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:691)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:943)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1336)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:402)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:359)
	at java.lang.Thread.run(Thread.java:722)

And in the heap dumps I create I can see io.'netty.util.Recycler$WeakOrderQueue$Link' with retained size of 100%

I found this bug, but I'm not sure it's relevant to my problem:
https://github.com/netty/netty/issues/3166

**Comment by mastercoms** [comment]
I have fixed some memory leaks related to not releasing some ByteBufs.
