### ISSUE TITLE
Internationalization framework

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#873]
In order for internationalization to be implemented, there needs to be a framework put in place.

This issue excludes actually converting all the English strings used around Glowstone to the framework in question. That task is bound by issue #297.

**Comment by Pr0methean** [comment]
Why not just use a ResourceBundle?

**Comment by volcanopowder** [comment]
I would consider shipping Glowstone with a directory of localization files that can be parsed quickly (perhaps JSON or YAML format) and then using whichever set is set in the configuration. There could then just be a simple localization manager using a method or static variables for the messages instead of hard-coded variables. 

Does anyone know if the client transmits a language packet?

**Comment by mastercoms** [comment]
Hi, this issue hasn't been updated but we've made significant progress on internationalization since then. We already have a framework for loading localized resources and using client locales where applicable.

**Comment by aramperes** [comment]
Closing because we've had a framework in place for a while. Refer to #297 for the conversion of the existing strings to said framework.
