### ISSUE TITLE
NMS and OBC support

### ISSUE THREAD

**Issue by leonardo-dgs** [GlowstoneMC/Glowstone#956]
Without net.minecraft.server and org.bukkit.craftbukkit classes, there are few plugins that can run on Glowstone server, and this makes it unusable even for lobbies, creative and minigames servers.
For example Essentials uses NMS, so it can't run on Glowstone

**Comment by hafarooki** [comment]
See: Linkstone

**Comment by hafarooki** [comment]
Also, I recommend not using essentials...

**Comment by mastercoms** [comment]
Essentials should work fine with Glowstone. What fork are you using and what components?

And yes, exposing nms and obc through Glowstone is being done in [Linkstone](https://github.com/GlowstoneMC/Linkstone).

**Comment by pisaiah** [comment]
![image](https://user-images.githubusercontent.com/16439221/43018229-f74e3632-8c26-11e8-938a-24af535a7e93.png)
[Linkstone](https://github.com/GlowstoneMC/Linkstone) provides support for NMS/OBC.
If Essentials doesn't work, you could try my [Bssentials](https://dev.bukkit.org/projects/bssentials) (3.x builds) full compatibility with Glowstone & (most of) Essentials API 
[_](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUzLSRwFkNvGFAcvlr5ZPaAxI_AfbQng904Ci_pE242aNsLir6)

**Comment by leonardo-dgs** [comment]
@mastercoms I'm using EssentialsX

**Comment by leonardo-dgs** [comment]
@IsaiahPatton How do I install Linkstone?

**Comment by aramperes** [comment]
Linkstone is currently work-in-progress. There is no artifact available for it.

You can follow the development of the Linkstone compiler by @aki-ks [here](https://github.com/GlowstoneMC/Linkstone/pull/4).

@IsaiahPatton started implementing some NMS components [here](https://github.com/GlowstoneMC/Linkstone/pull/5), which will need to be adapted to Aki's compiler once it is ready.

I'm closing this issue because discussion regarding individual plugin support (through NMS/OBC implementation) is better suited for the Linkstone repo.
