### ISSUE TITLE
Unimplemented but important

### ISSUE THREAD

**Issue by niansa** [GlowstoneMC/Glowstone#992]
Both Command Blocks and pressure plates are very important but not yet implemented...

**Comment by aramperes** [comment]
There is an issue about command blocks here: #338. Note that the [command blocks branch](https://github.com/GlowstoneMC/Glowstone/tree/command-blocks) exists but is severely out of date.

We don't usually open issues about specific missing features like "[x doesn't work](https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#insert-feature-here-doesnt-work)" because Glowstone is a work-in-progress project. Rather, we prefer having issues detailing how to implement a specific features (see the Command blocks issue).
